const fs = require('fs');
const path = require('path');

// Try to load from .env file if it exists (useful for local development)
const envPath = path.join(__dirname, '.env');
let localEnv = {};
if (fs.existsSync(envPath)) {
    const envFile = fs.readFileSync(envPath, 'utf-8');
    envFile.split('\n').forEach(line => {
        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
            localEnv[match[1]] = match[2] || '';
        }
    });
}

// Vercel environment variables take precedence over local .env
const apiBase = process.env.PROD_API_BASE || localEnv.PROD_API_BASE || 'http://127.0.0.1:8000';

const content = `// Auto-generated by build.js\nconst API_BASE = "${apiBase}";\n`;
fs.writeFileSync(path.join(__dirname, 'js', 'env.js'), content);
console.log('Successfully generated js/env.js with API_BASE:', apiBase);
